/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.CRUD;


/**
 *
 * @author EDULALO
 */
public class Crud_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Crud
     */
    public Crud_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarUsu = new javax.swing.JButton();
        BuscarUsu = new javax.swing.JButton();
        EditarUsu = new javax.swing.JButton();
        EliminarUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AgregarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregar-usuario.png"))); // NOI18N
        AgregarUsu.setText("Agregar Usuario");
        AgregarUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuActionPerformed(evt);
            }
        });

        BuscarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/buscar-usuario.png"))); // NOI18N
        BuscarUsu.setText("Buscar Usuario");
        BuscarUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuscarUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUsuActionPerformed(evt);
            }
        });

        EditarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/editar-usuario.png"))); // NOI18N
        EditarUsu.setText("Editar Usuario");
        EditarUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuActionPerformed(evt);
            }
        });

        EliminarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar usuario.png"))); // NOI18N
        EliminarUsu.setText("Eliminar Usuario");
        EliminarUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/usuario.png"))); // NOI18N
        jLabel1.setText("Usuario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/returnbackredoarrow_82934.png"))); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EditarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgregarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BuscarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EliminarUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuActionPerformed
        // TODO add your handling code here:
        CrearUsuario Cuser= new CrearUsuario();
        Cuser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarUsuActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_VolverActionPerformed

    private void EliminarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuActionPerformed
        // TODO add your handling code here:
        Eliminar_Usuario abrir=new Eliminar_Usuario();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarUsuActionPerformed

    private void BuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUsuActionPerformed

    }//GEN-LAST:event_BuscarUsuActionPerformed

    private void EditarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuActionPerformed
    EditarUsuario editor = new EditarUsuario();
    editor.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_EditarUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUsu;
    private javax.swing.JButton BuscarUsu;
    private javax.swing.JButton EditarUsu;
    private javax.swing.JButton EliminarUsu;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
